import { apiBaseUrl } from "@/lib/api/publish-client";
import {
  buildGeneratedApiModels,
  type GeneratedApiEndpoint
} from "@/lib/api/generated-api";
import type {
  ParsedSchema,
  PublishedApi,
  SchemaCodeFormat,
  SchemaGroup
} from "@/types/schema";
import { downloadTextFile, slugifyIdentifier } from "@/lib/utils";

export type ExportKind = "json" | "postman" | "code" | "png" | "pdf";

export interface ExportResult {
  ok: boolean;
  message: string;
}

export interface SourceExportPayload {
  schemeName: string;
  schema: ParsedSchema;
  code: string;
  format: SchemaCodeFormat;
  nodePositions: Record<string, { x: number; y: number }>;
  groups: SchemaGroup[];
  publishedApi?: PublishedApi | null;
}

function timestampSlug() {
  return new Date().toISOString().replace(/[:.]/g, "-");
}

function fileBaseName(name: string) {
  return slugifyIdentifier(name || "graphdb-schema") || "graphdb-schema";
}

function createCollectionId() {
  return globalThis.crypto?.randomUUID?.() || `graphdb-${timestampSlug()}`;
}

function apiRootUrl() {
  return apiBaseUrl().replace(/\/+$/, "").replace(/\/api$/, "");
}

function postmanBaseUrl() {
  return apiRootUrl();
}

function postmanPathTemplate(path: string) {
  const normalizedPath = path.startsWith("/") ? path : `/${path}`;
  return normalizedPath.replace(/\{([^}]+)\}/g, ":$1");
}

function postmanUrlObject(endpoint: GeneratedApiEndpoint) {
  const rawBase = `{{API_BASE_URL}}${postmanPathTemplate(endpoint.path)}`;
  const rawQuery = endpoint.query
    .map((parameter) => `${parameter.key}=${parameter.value}`)
    .join("&");

  return {
    raw: rawQuery ? `${rawBase}?${rawQuery}` : rawBase,
    host: ["{{API_BASE_URL}}"],
    path: postmanPathTemplate(endpoint.path)
      .replace(/^\/+/, "")
      .split("/")
      .filter(Boolean),
    query: endpoint.query.map((parameter) => ({
      key: parameter.key,
      value: parameter.value
    })),
    variable: endpoint.pathParams.map((parameter) => ({
      key: parameter.key,
      value: parameter.value
    }))
  };
}

function postmanRequestDescription(endpoint: {
  description: string;
  sampleLabel: string;
  sample: string;
}) {
  return `${endpoint.description}\n\n${endpoint.sampleLabel}:\n${endpoint.sample}`;
}

export function exportSource(
  kind: "json" | "postman" | "code",
  payload: SourceExportPayload
): ExportResult {
  const stamp = timestampSlug();
  const baseName = fileBaseName(payload.schemeName);

  if (kind === "json") {
    downloadTextFile(
      `${baseName}-${stamp}.json`,
      JSON.stringify(
        {
          name: payload.schemeName,
          format: payload.format,
          code: payload.code,
          schema: payload.schema,
          nodePositions: payload.nodePositions,
          groups: payload.groups
        },
        null,
        2
      ),
      "application/json"
    );
    return { ok: true, message: "Schema JSON exported." };
  }

  if (kind === "postman") {
    const baseUrl = postmanBaseUrl();
    const apiModels = buildGeneratedApiModels(payload.schema.tables, {
      publishedApi: payload.publishedApi
    });
    const collection = {
      info: {
        _postman_id: createCollectionId(),
        name: `${payload.schemeName} CRUD API`,
        description:
          "Generated by GraphDB Studio. If this schema is not published yet, update the `apiToken` collection variable after publishing.",
        schema:
          "https://schema.getpostman.com/json/collection/v2.1.0/collection.json"
      },
      auth: {
        type: "bearer",
        bearer: [
          {
            key: "token",
            value: "{{apiToken}}",
            type: "string"
          }
        ]
      },
      variable: [
        {
          key: "API_BASE_URL",
          value: baseUrl,
          type: "string"
        },
        {
          key: "apiToken",
          value: payload.publishedApi?.apiToken || "paste-your-api-token-here",
          type: "string"
        }
      ],
      item: apiModels.map((model) => ({
        name: model.title,
        description: `CRUD requests for ${model.title}.`,
        item: model.endpoints.map((endpoint) => ({
          name: endpoint.name,
          request: {
            method: endpoint.method,
            header: [
              {
                key: "Accept",
                value: "application/json",
                type: "text"
              },
              ...(endpoint.body
                ? [
                    {
                      key: "Content-Type",
                      value: "application/json",
                      type: "text"
                    }
                  ]
                : [])
            ],
            description: postmanRequestDescription(endpoint),
            url: postmanUrlObject(endpoint),
            body: endpoint.requestBodyRaw
              ? {
                  mode: "raw",
                  raw: endpoint.requestBodyRaw,
                  options: {
                    raw: {
                      language: "json"
                    }
                  }
                }
              : undefined
          },
          response: []
        }))
      }))
    };

    downloadTextFile(
      `${baseName}-${stamp}.postman_collection.json`,
      JSON.stringify(collection, null, 2),
      "application/json"
    );

    return { ok: true, message: "Postman collection exported." };
  }

  const extension = payload.format === "dbml" ? "dbml" : "sql";
  downloadTextFile(`${baseName}-${stamp}.${extension}`, payload.code);
  return { ok: true, message: "Source code exported." };
}

export async function exportCanvasImage(
  kind: "png" | "pdf",
  element: HTMLElement,
  schemeName: string
): Promise<ExportResult> {
  const [{ toPng }, { jsPDF }] = await Promise.all([
    import("html-to-image"),
    import("jspdf")
  ]);
  const stamp = timestampSlug();
  const baseName = fileBaseName(schemeName);
  const width = element.offsetWidth;
  const height = element.offsetHeight;
  const dataUrl = await toPng(element, {
    pixelRatio: 2.2,
    backgroundColor: "#070707",
    cacheBust: true,
    width,
    height,
    filter: (node) => {
      if (!(node instanceof HTMLElement)) {
        return true;
      }

      return !(
        node.dataset.exportExclude === "true" ||
        node.classList.contains("react-flow__controls") ||
        node.classList.contains("react-flow__attribution") ||
        node.classList.contains("react-flow__panel")
      );
    },
    style: {
      background: "#070707"
    }
  });

  if (kind === "png") {
    const link = document.createElement("a");
    link.href = dataUrl;
    link.download = `${baseName}-${stamp}.png`;
    document.body.appendChild(link);
    link.click();
    link.remove();
    return { ok: true, message: "Schema PNG exported." };
  }

  const orientation = width >= height ? "landscape" : "portrait";
  const pdf = new jsPDF({
    orientation,
    unit: "px",
    format: [width, height],
    compress: true
  });

  pdf.addImage(dataUrl, "PNG", 0, 0, width, height);
  pdf.save(`${baseName}-${stamp}.pdf`);
  return { ok: true, message: "Schema PDF exported." };
}
